apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: payflow
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: payflow_db
  DB_USER: payflow_user
  DB_PASSWORD: PayFlow@2025

