apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: payflow
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/payflow_db"
  SPRING_DATASOURCE_USERNAME: "payflow_user"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  # Service URLs for API Gateway
  ACCOUNT_SERVICE_URL: "http://account-service:8081"
  TRANSACTION_SERVICE_URL: "http://transaction-service:8082"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8083"

